# Site settings
title: jecodeenchaussettes - Nouveaux concepte
description: Ici je vos presente la nouvelle mode du bien-être avec jecodeenchaussettes.com le site de référence.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: jecodeenchaussettes
user_description: le concepte est simple jecodeenchaussettes et j'aime sa;
user_title: je code en chaussettes en claire.
email: jecodeenchaussettes.orleans@gmail.com
twitter_username: jecodenchausset
github_username:  jecodeenchaussettesorleans
gplus_username:  YaLlQE
fb_username: Jecodeenchaussettes-1449116961825990

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
